"""baseline — existing schema prior to plan/entitlement evolution

This is the Alembic baseline for an already-deployed database. It intentionally
does NOT create the existing tables (companies, users, roles, audit_logs, etc.):
those already exist in production and were created via the dev-init / manual
path before Alembic was introduced. Stamp an existing database to this revision
(`alembic stamp 0001_baseline`) so subsequent migrations apply cleanly.

For a brand-new database, generate the full initial schema as a separate
autogenerated revision on top of this baseline, or run dev-init first then stamp.

Revision ID: 0001_baseline
Revises:
"""
from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # No-op: existing schema is already present in the target database.
    pass


def downgrade() -> None:
    # No-op: refuse to drop pre-existing production schema from the baseline.
    pass
